name: SSH

on:
  workflow_dispatch:
jobs:
      run_example_job:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
          - name: print out example job
            uses: appleboy/ssh-action@v1.0.0
            with:
              host: '158.160.127.41'
              username: ${{ secrets.USERNAME }}
              key: ${{ secrets.KEY }}
              port: ${{ secrets.PORT }}
              passphrase: ${{ secrets.PASSPHRASE }}
              command_timeout: 30m
              script_stop: true
              script: |
                echo "Nice Job!!!"
                whoami
