name: SSH transfer file
on:
  workflow_dispatch:
jobs:
  build:
     name: Build
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - name: print out example job
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 158.160.127.41
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "./docker-compose.yaml"
          target: /var