name: Docker Image Publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
     contents: read
     packages: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name and username
        run: | 
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          echo "defaultContext = {{defaultContext}}"

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
              push: true
              tags: ghcr.io/${{ env.REPO }}:account:${{ github.sha }}
              context: "{{defaultContext}}:account"
              #file: ./account/Dockerfile`


