name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  run_unittests_account:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        #working-directory: .github/account
        run: | 
          python3 -m pip install --upgrade pip
          python3 -m pip install -r account/requirements.txt

      - name: Run Tests
        run: |
          cd ./account/app
          #echo "SECRET_KEY = 'django-insecure-dummy-secret'" > ./proj/secrets.py
          python3 manage.py test
  run_unittests_profile:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          cd ./profile/app
          #echo "SECRET_KEY = 'django-insecure-dummy-secret'" > ./proj/secrets.py
          python3 manage.py test
 

  build-and-push-account:
    runs-on: ubuntu-latest
    needs: run_unittests_account
    steps:
      - uses: actions/checkout@v2
      - uses: raisultan/ycr-push@main
        env:
          KEY_JSON: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          REGISTRY_ID: crpq5hg8snv82fhgppum
          DOCKERFILE_PATH: ./account
          IMAGE_NAME: my-cr-repo_miniwork_account
          IMAGE_TAG: ${{ github.sha }}

  build-and-push-profile:
    runs-on: ubuntu-latest
    needs: run_unittests_profile
    steps:
      - uses: actions/checkout@v2
      - uses: raisultan/ycr-push@main
        env:
          KEY_JSON: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          REGISTRY_ID: crpq5hg8snv82fhgppum
          DOCKERFILE_PATH: ./profile
          IMAGE_NAME: my-cr-repo_miniwork_profile
          IMAGE_TAG: ${{ github.sha }}

  build-and-push-engix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: raisultan/ycr-push@main
        env:
          KEY_JSON: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          REGISTRY_ID: crpq5hg8snv82fhgppum
          DOCKERFILE_PATH: ./eginx
          IMAGE_NAME: my-cr-repo_miniwork_enginx
          IMAGE_TAG: ${{ github.sha }}

