name: SSH transfer file

on:
  workflow_dispatch:
jobs:
  run_example_job:
    name: print out example job
    uses: appleboy/scp-action@v0.1.4
    with:
      host: 158.160.127.41
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.KEY }}
      port: ${{ secrets.PORT }}
      passphrase: ${{ secrets.PASSPHRASE }}
      source: "docker-compose.yaml, docker-compose.yaml"
      target: /home