name: Python package

on: [push]

jobs:
  run_unittests:
    runs-on: ubuntu-latest
    env:
      working-directory: ./account
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        run: ls -R
        working-directory: ${{env.working-directory}}
      - name: Install dependencies  
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
