name: Docker Image Publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
          #${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:account"
          push: true
          tags: user/app:latest
          #tags: ${{ steps.meta.outputs.tags }}
          #labels: ${{ steps.meta.outputs.labels }}
          #github-token: ${{ secrets.GITHUB_TOKEN }}




      # Build and push Docker image with Buildx (don't push on PR)


    #- name: Yandex Cloud CR "Login" Action for GitHub Actions
    #  uses: yc-actions/yc-cr-login@v1
    #  with:
    #    yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    #- name: Build, tag, and push image to Yandex Cloud Container Registry
    #  env:
    #    CR_REGISTRY: crpq5hg8snv82fhgppum
    #    CR_REPO: my-cr-repo-miniwork-account
    #    IMAGE_TAG: ${{ github.sha }}
    #  run: |
    #    account/docker build -t cr.yandex/$CR_REGISTRY/$CR_REPO:$IMAGE_TAG .
    #    account/docker push cr.yandex/$CR_REGISTRY/$CR_REPO:$IMAGE_TAG




   
   # - name: Yandex Cloud CR "Login" Action for GitHub Actions
   #   uses: yc-actions/yc-cr-login@v1
    #  with:
    #    yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
    #- name: Build, tag, and push image to Yandex Cloud Container Registry
    #  env:
    #    CR_REGISTRY: crpq5hg8snv82fhgppum
    #    CR_REPO: my-cr-repo-miniwork-account
    #    IMAGE_TAG: ${{ github.sha }}
     # run: |
    #    account/docker build -t cr.yandex/$CR_REGISTRY/$CR_REPO:$IMAGE_TAG .
    #    account/docker push cr.yandex/$CR_REGISTRY/$CR_REPO:$IMAGE_TAG












       
          
          
          
          
          

