name: Docker Image Publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
env:
           CR_REGISTRY: crpq5hg8snv82fhgppum
           CR_REPOSITORY: my-cr-repo_miniwork_nginx
           IMAGE_TAG: ${{ github.sha }}
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
     contents: read
     packages: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #- name: Login to GitHub Container Registry
      #  uses: docker/login-action@v3
      #  with:
      #      registry: ghcr.io
      #      username: ${{ github.actor }}
      #      password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Yandex Container Registry
        uses: yc-actions/yc-cr-login@v1
        with:
            yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

        #run: |
        #  docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
        #  docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG




      - name: Lowercase the repo name and username
        run: | 
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          echo "defaultContext = {{defaultContext}}"

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
              push: true
              tags: cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
              #labels: account
          #/account/${{ github.sha }}
              context: "{{defaultContext}}:account"
              #file: ./account/Dockerfile`


