name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  run_unittests_account:
   runs-on: ubuntu-latest
   strategy:
    max-parallel: 4
    matrix:
      python-version: [ '3.10' ]
      steps:
      - name: Check out repository code
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
      - run: echo $GITHUB_WORKSPACE
      - name: Main
      - context: ./account
        run: |
          python -m pip install --upgrade pip setuptools wheel
          
          pip install -r requirements.txt
