name: Pull request coverage verification
on: [pull_request]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Django Coverage GitHub Action
        uses: dc740/django-coveragepy-github-action@0.9
        with:
          django-app: 'YOUR_DJANGO_APPLICATION_NAME_HERE'
          minimum-coverage: '40'